### ISSUE TITLE
Container solution

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#10]
A container solution is not presented in the first version

**Comment by fgasnier71** [comment]
@JelmerDL  can you write the details regarding how the algorithm ought to sort crates (by height, then by length + width) and how should we decide which container to pick next.
For example, I guess that:
- if the crate to stack would fit in 40 Standard it should create one (as all following crates will be smaller) rather than 40 HC. 
- it should test if the remaining crates would fit in 20' container before creating new 40' container.

**Comment by JelmerDL** [comment]
- Default will be to fill 40'HC, because it's the most economical way to ship in 80% of the cases.
- If frame crate #1 contains 8 layers or less it can be chopped in height to fit a box container instead of a High Cube.
- First start filling containers with the largest crates then stack the smaller behind.
- Keep in mind that glass crates can sit next to each other. Small glass crates can also be stacked in 40'HC containers.
- An extreme size glass crate always needs a 20' Open Top, two will need a 40' OT, three a 20' OT + 40' OT and so on.
- It is always good to test the fill rate of the final container and see if a 20' would make more sense than a 40' for the remaining crates: (Total length of crates) / (inside lenght of 40' container) =< 0,5 then use 20' container)
