### ISSUE TITLE
Manually filled excel won't load

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#30]
When loading a manual excel file, the input remains empty

![image](https://user-images.githubusercontent.com/78344754/115726418-01224b00-a383-11eb-8b99-346f01df0a13.png)

[test.xlsx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6358807/test.xlsx)

@fgasnier71 Does this have to do with the data formatting? Or could you provide an input-template that we can manually fill?

**Comment by fgasnier71** [comment]
@JelmerDL 
The file was ill-formed.
Please, use the character (') when entering strings containing only digits otherwise the entry is recognized as a double in Excel.
You can also notice that strings are aligned on the left whereas doubles are aligned to the right.

Find the enclosed corrected file attached.
[test.xlsx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6358997/test.xlsx)

If you need a less picky format this needs to be discussed in another issue.

**Comment by JelmerDL** [comment]
Thanks @fgasnier71 it works for now. Perhaps we can fix it at a later stage.
