### ISSUE TITLE
Critical error with oversized glass

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#31]
![image](https://user-images.githubusercontent.com/78344754/115827825-2196e780-a40d-11eb-912e-522e9922effb.png)

Program crashes with glass units >2150mm short side. Instead it should pack into an appropriate crate (crate 6) or give an error message.

See attached excel file.
[Puidelen - failing glass.xlsx](https://github.com/treeDiM/MHBCrateLoadDesigner/files/6363266/Puidelen.-.failing.glass.xlsx)

**Comment by fgasnier71** [comment]
@JelmerDL The issue occurs because of the repacking action that is attempting to fill the smaller cases when possible.
 The algorithm does the following:
- sort glasses by decreasing long side then ShortSide,
- fill crates, creating new crates as needed (when the current crate does not fit or is full),
- empty all crates and sort them in the reverse order (mostly from smaller to bigger?),
- sort glasses by increasing long side then increasing short side,
- try to fit them in previously creating crates -> This fails because some glass has taken the 2733x2598 glass place.

This algorithm fails because sorting with 2 dimensions is prone to problems.

What should I do?
Should I cancel the attempt to fill smaller crates first when described algorithm fails?

**Comment by fgasnier71** [comment]
Chose to avoid glass crates repack when it fails.
